# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
resources:
  packages:
   - package: nugetPackage
     type: Nuget
     version: 2.0.0
     connection: 'nuget publish'
     name: nugetTest/OctocatApp
     trigger: true
pool:
  name: harks

steps:
- task: DownloadGitHubNugetPackage@1
  inputs:
    packageName: 'harshiniks/OctocatApp'
    externalEndpoints: 'f29fce22-5f43-4c06-85bb-8e1452eb78db'
    version: '2.0.0'
